CREATE DATABASE IF NOT EXISTS ai_cube_portfolio;
USE ai_cube_portfolio;

CREATE TABLE IF NOT EXISTS about (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  title VARCHAR(120) NOT NULL,
  bio TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  tech_stack VARCHAR(255) NOT NULL,
  github_link VARCHAR(255),
  live_link VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS skills (
  id INT PRIMARY KEY AUTO_INCREMENT,
  category VARCHAR(120) NOT NULL,
  skill_name VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS experience (
  id INT PRIMARY KEY AUTO_INCREMENT,
  role VARCHAR(160) NOT NULL,
  company VARCHAR(160) NOT NULL,
  duration VARCHAR(120) NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS education (
  id INT PRIMARY KEY AUTO_INCREMENT,
  degree VARCHAR(160) NOT NULL,
  institution VARCHAR(180) NOT NULL,
  year VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS contact (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(80) NOT NULL,
  value VARCHAR(255) NOT NULL
);
